In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
#data=pd.read_csv("~/Downloads/Demo_Data-Demo/21013_0_CDR3Length.csv",sep='\t',index_col=0,names="X")
#data=pd.read_csv("~/Downloads/Demo_Data-Demo/25671_CDRs.csv",usecols=["Freq"])
#data=pd.read_csv("~/Downloads/Demo_Data-Demo/21551_CDR3_list_1.csv",header=None)
data=pd.read_csv("data2.csv")
#data.columns=["CDR3",'Freq']
data

Unnamed: 0    frq       CDRs      frq2
0             0     32   000697H3  0.001011
1             1     42   000698H3  0.001327
2             2     47   000699H3  0.001485
3             3     40   000700H3  0.001264
4             4     38   000701H3  0.001201
5             5     33   000987H3  0.001043
6             6     49   000989H3  0.001548
7             7     45   000998H3  0.001422
8             8     39   000999H3  0.001232
9             9     31   001000H3  0.000979
10           10     44   001001H3  0.001390
11           11     41   001002H3  0.001295
12           12     30   001003H3  0.000948
13           13     56   001005H3  0.001769
14           14     31   001037H3  0.000979
15           15     64   001038H3  0.002022
16           16     29   001039H3  0.000916
17           17     29   001042H3  0.000916
18           18     43   001045H3  0.001359
19           19     54   001049H3  0.001706
20           20     41   001080H3  0.001295
21           21     35   001081H3  0.001106
22           22     43   001082H3  0.001359
23           23     45   001084H3  0.001422
24           24     29   001085H3  0.000916
25           25     26   001090H3  0.000822
26           26     37   001091H3  0.001169
27           27     22   001092H3  0.000695
28           28     45   001093H3  0.001422
29           29     25   001094H3  0.000790
..          ...    ...        ...       ...
876         876     21   004345H3  0.000664
877         877     30   004346H3  0.000948
878         878     13   004347H3  0.000411
879         879     19   004348H3  0.000600
880         880     31  1002022H3  0.000979
881         881     27  1002028H3  0.000853
882         882     19  1002030H3  0.000600
883         883     28  1002031H3  0.000885
884         884     29  1002032H3  0.000916
885         885     31  1002033H3  0.000979
886         886     37  1003554H3  0.001169
887         887     18  1003558H3  0.000569
888         888     25  1003559H3  0.000790
889         889     37  1003562H3  0.001169
890         890     34  1003564H3  0.001074
891         891     34  1003566H3  0.001074
892         892     15  1003570H3  0.000474
893         893     21  1003571H3  0.000664
894         894     31  1003572H3  0.000979
895         895     34  1003577H3  0.001074
896         896     18  1003579H3  0.000569
897         897     24  1003581H3  0.000758
898         898     98  1003584H3  0.003096
899         899     21  1003586H3  0.000664
900         900     27  1003592H3  0.000853
901         901     15  1003593H3  0.000474
902         902     17  1003594H3  0.000537
903         903     15  1003595H3  0.000474
904         904     13  1003596H3  0.000411
905         905  31649        NaN       NaN

[906 rows x 4 columns]

In [6]:
n=len(data) # data.shape[0]
if n>10000:
    data=data.loc[0:10000-1]
    n=len(data)
    
r=data.frq
totalReads=sum(r)

In [7]:
totalReads

63298

In [8]:
p=r/sum(r)
-sum(p*np.log2(p))

5.8059736494529437

In [9]:
totalReads50=round(totalReads/2)
totalReads50

31649.0

In [13]:
y = np.zeros(n+1,dtype=np.int32)
y[1]=r[0]
for i in range(2,n+1):
    y[i]=y[i-1]+r[i-1]
    if y[i-1]<totalReads50:
        if y[i]>totalReads50:
            print "found 50%! i=",i
            DI=i*100/n
            print "DI={:.1f}".format(DI) 

In [14]:
k=np.arange(n+1)
k

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [15]:
x=k/n
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [16]:
y0 = np.zeros(n+1)
y0=k/n*sum(r)
y0

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,

In [17]:
plt.figure(figsize=(6,6))
plt.plot(x*100,y/max(y)*100,'b.-')
plt.plot(x*100,y0/max(y0)*100,'g.--')
plt.grid(True)
plt.rc('grid', linestyle="--", color='black')
plt.xlabel("Percentage of total reads")
plt.ylabel("Percentage of unique CDR3s")
plt.title('D.I.={:.1f}'.format(DI))

NameError: name 'DI' is not defined